version: "3.9"
services:
  web:
    image: nginx
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./framework/public:/var/www/framework/public
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./framework:/var/www/framework
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: mariadb:10.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: framework
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql